### ISSUE TITLE
Sync failing for CHOP bucket

### ISSUE THREAD

**Issue by clarisse-lau** [Sage-Bionetworks/s3-synapse-sync#48]
The lambda function to sync files from an AWS S3 bucket to Synapse was recently enabled for the HTAN CHOP bucket (s3://htan-dcc-chop): https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/562

I copied a number of files into the `s3://htan-dcc-chop/single_cell_ATACseq_level_1_CLEAN/` folder, and see on [Synapse](https://www.synapse.org/#!Synapse:syn51179721) that the folder and subfolders were generated as expected, but filehandles have not been created. 

@BrunoGrandePhD, would you be able to help us look into the logs for any errors that may have come up? 
(cc @adamjtaylor)

**Comment by BrunoGrandePhD** [comment]
I'm confirming that errors occurred between 10 AM and 1 PM today (March 6th). 

![image](https://user-images.githubusercontent.com/740725/223278157-e7b0f106-9216-44a4-857b-7d86a1741b72.png)

In the CloudWatch logs, all of the requests seem to be failing with the same `SynapseHTTPError`. Here's a representative error message and stack trace: 

```
[ERROR] SynapseHTTPError: 403 Client Error: 
Only the creator of ExternalS3StorageLocationSetting.id=41127 can create an external S3FileHandle with storageLocationId = 41127
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 65, in lambda_handler
    sync_to_synapse(bucket,event,eventname,filename,key)
  File "/var/task/lambda_function.py", line 121, in sync_to_synapse
    create_filehandle(syn, event, filename, bucket, key, project_id)
  File "/var/task/lambda_function.py", line 150, in create_filehandle
    fileHandle = syn.restPOST('/externalFileHandle/s3', json.dumps(fileHandle), endpoint=syn.fileHandleEndpoint)
  File "/var/task/synapseclient/client.py", line 3913, in restPOST
    response = self._rest_call('post', uri, body, endpoint, headers, retryPolicy, requests_session, **kwargs)
  File "/var/task/synapseclient/client.py", line 3880, in _rest_call
    self._handle_synapse_http_error(response)
  File "/var/task/synapseclient/client.py", line 3850, in _handle_synapse_http_error
    exceptions._raise_for_status(response, verbose=self.debug)
  File "/var/task/synapseclient/core/exceptions.py", line 160, in _raise_for_status
    raise SynapseHTTPError(message, response=response)
```

I hope this is enough to help you debug the issue! If you need more help, let me know and I'll loop in my project manager so we can set aside some time.

**Comment by clarisse-lau** [comment]
Ah that rings a bell!

The Synapse account `synapse-service-HTAN-lambda` has to be the one to attach the S3 bucket to the Synapse project in order to create filehandles pointing to that bucket. 

The files are showing up now. Thanks @BrunoGrandePhD!
![Screenshot 2023-03-06 at 3 40 21 PM](https://user-images.githubusercontent.com/63608514/223281688-347952a4-2dd5-4d79-95bf-07a9c465e998.png)
